#!/bin/bash
echo "Start"
export TIKTRACK_DEV_MODE="true"
export TIKTRACK_CACHE_DISABLED="false"
echo "Environment variables set"
echo "TIKTRACK_DEV_MODE: $TIKTRACK_DEV_MODE"
echo "TIKTRACK_CACHE_DISABLED: $TIKTRACK_CACHE_DISABLED"
echo "End"
exit 0


