#!/usr/bin/env python3
"""Regenerate agents_os/ui/js/pipeline-gate-map.generated.js from gates.yaml (WP004)."""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from agents_os_v2.ssot.gate_mapping import GATE_ALIASES  # noqa: E402


def render_js() -> str:
    # Single line JSON for compact file
    payload = json.dumps(GATE_ALIASES, sort_keys=True, separators=(",", ":"))
    return (
        "/* AUTO-GENERATED by agents_os_v2/tools/generate_gate_map_assets.py — do not edit */\n"
        "/* SSOT: agents_os_v2/ssot/gates.yaml (WP004 KB-66) */\n"
        f"window.__PHOENIX_LEGACY_GATE_MAP = {payload};\n"
    )


def main() -> int:
    out = REPO_ROOT / "agents_os" / "ui" / "js" / "pipeline-gate-map.generated.js"
    out.write_text(render_js(), encoding="utf-8")
    print(f"Wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
