idx_alerts_created_at                       
idx_alerts_is_triggered                     
idx_alerts_related_type_id                  
idx_alerts_status                           
idx_constraints_active                      
idx_constraints_table_column                
idx_constraints_type                        
idx_data_refresh_logs_operation_type        
idx_data_refresh_logs_provider              
idx_data_refresh_logs_start_time            
idx_data_refresh_logs_status                
idx_enum_active                             
idx_enum_constraint_id                      
idx_enum_sort                               
idx_intraday_data_slots_slot_start_utc      
idx_intraday_data_slots_ticker_provider_slot
idx_market_data_quotes_asof_utc             
idx_market_data_quotes_fetched_at           
idx_market_data_quotes_stale                
idx_market_data_quotes_ticker_provider      
idx_preference_profiles_user_active         
idx_preference_types_active                 
idx_user_preferences_v3_complex             
idx_user_preferences_v3_lookup              
idx_validation_active                       
idx_validation_constraint_id                
idx_validation_type                         
ix_cash_flows_id                            
ix_currencies_id                            
ix_executions_id                            
ix_note_relation_types_id                   
ix_preference_profiles_id                   
ix_tickers_id                               
ix_tickers_symbol                           
sqlite_autoindex_currencies_1               
sqlite_autoindex_external_data_providers_1  
sqlite_autoindex_note_relation_types_1      
sqlite_autoindex_preference_groups_1        
sqlite_autoindex_preference_types_1         
sqlite_autoindex_user_preferences_v3_1      
sqlite_autoindex_users_1                    
sqlite_autoindex_users_2                    
ux_intraday_data_slots_ticker_provider_slot 
