#!/usr/bin/env python3
"""
Update HTML pages with new script loading code
Code Review Fix - Phase 2: Replace async with defer in all HTML pages

This script updates all HTML pages to use the new defer-only script loading
generated by generate-script-loading-code.js
"""

import os
import re
import subprocess
from pathlib import Path

# Project paths
PROJECT_ROOT = Path(__file__).parent.parent
TRADING_UI = PROJECT_ROOT / "trading-ui"

# Pages to update (from PAGES_LIST.md main pages)
MAIN_PAGES = [
    'index.html', 'trades.html', 'trade_plans.html', 'alerts.html',
    'tickers.html', 'ticker-dashboard.html', 'trading_accounts.html',
    'executions.html', 'data_import.html', 'cash_flows.html', 'notes.html',
    'research.html', 'ai-analysis.html', 'watch-list.html', 'preferences.html',
    'user-profile.html'
]

def update_page_html(page_file):
    """Update a single page's HTML with new script loading code"""
    page_name = page_file.stem  # Remove .html extension

    print(f"🔄 Updating {page_file.name}...")

    try:
        # Generate new script loading code
        result = subprocess.run([
            'node', 'trading-ui/scripts/generate-script-loading-code.js', page_name
        ], cwd=str(PROJECT_ROOT), capture_output=True, text=True)

        if result.returncode != 0:
            print(f"❌ Failed to generate script loading for {page_name}: {result.stderr}")
            return False

        new_script_html = result.stdout.strip()

        # Read current HTML
        with open(page_file, 'r', encoding='utf-8') as f:
            current_html = f.read()

        # Find the start of script loading section
        start_pattern = r'<!-- =+ START SCRIPT LOADING ORDER =+ -->'
        start_match = re.search(start_pattern, current_html)

        if start_match:
            # Find the end - look for page-specific scripts or </head>
            end_patterns = [
                r'<script src="scripts/page-initialization-configs',
                r'</head>'
            ]

            end_pos = len(current_html)
            for pattern in end_patterns:
                match = re.search(pattern, current_html[start_match.end():])
                if match:
                    end_pos = start_match.end() + match.start()
                    break

            # Replace the script loading section
            updated_html = current_html[:start_match.start()] + new_script_html + current_html[end_pos:]
        else:
            # Try to find old async section
            old_async_pattern = r'<!-- \[1\] Load Order: 1 \| Strategy: async -->'
            old_match = re.search(old_async_pattern, current_html)

            if old_match:
                # Find end of old section
                end_patterns = [
                    r'<script src="scripts/page-initialization-configs',
                    r'</head>'
                ]

                end_pos = len(current_html)
                for pattern in end_patterns:
                    match = re.search(pattern, current_html[old_match.end():])
                    if match:
                        end_pos = old_match.end() + match.start()
                        break

                updated_html = current_html[:old_match.start()] + new_script_html + current_html[end_pos:]
            else:
                print(f"⚠️ Could not find script loading section in {page_file.name}")
                return False

        # Write updated HTML
        with open(page_file, 'w', encoding='utf-8') as f:
            f.write(updated_html)

        # Verify no async scripts remain
        async_count = len(re.findall(r'<script[^>]*\sasync[^>]*>', updated_html))
        defer_count = len(re.findall(r'<script[^>]*\sdefer[^>]*>', updated_html))

        print(f"✅ Updated {page_file.name}: {async_count} async, {defer_count} defer scripts")

        return async_count == 0

    except Exception as e:
        print(f"❌ Error updating {page_file.name}: {e}")
        return False

def main():
    """Main function to update all HTML pages"""
    print("🔄 Updating HTML pages with defer-only script loading")
    print("=" * 60)

    updated_count = 0
    success_count = 0

    for page_name in MAIN_PAGES:
        page_file = TRADING_UI / page_name

        if not page_file.exists():
            print(f"⚠️ Page not found: {page_name}")
            continue

        if update_page_html(page_file):
            success_count += 1

        updated_count += 1

    print("\n📊 Summary:")
    print(f"   Pages processed: {updated_count}")
    print(f"   Successfully updated: {success_count}")
    print(f"   Failed: {updated_count - success_count}")

    if success_count == updated_count:
        print("\n✅ All pages updated successfully with defer-only loading!")
    else:
        print(f"\n⚠️ {updated_count - success_count} pages need manual review")

if __name__ == "__main__":
    main()
