#!/bin/bash
# בדיקות בדפדפן - Entity Details Modal
# Browser Testing Script for Entity Details Modal

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║  🧪 בדיקות בדפדפן - Entity Details Modal                    ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 עמודים לבדיקה:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "עמודים מרכזיים:"
echo "  • http://localhost:8080/trades"
echo "  • http://localhost:8080/executions"
echo "  • http://localhost:8080/trading_accounts"
echo "  • http://localhost:8080/db_display"
echo ""
echo "🧪 הוראות בדיקה:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. פתח כל עמוד בדפדפן"
echo "2. פתח את הקונסולה (F12)"
echo "3. הרץ את הפקודה הבאה בכל עמוד:"
echo ""
echo "   copy(JSON.stringify({"
echo "     showEntityDetails: typeof window.showEntityDetails,"
echo "     entityDetailsModal: typeof window.entityDetailsModal,"
echo "     EntityDetailsAPI: typeof window.EntityDetailsAPI,"
echo "     EntityDetailsRenderer: typeof window.EntityDetailsRenderer,"
echo "     modalInitialized: window.entityDetailsModal?.isInitialized"
echo "   }))"
echo ""
echo "4. או הרץ את הסקריפט:"
echo "   trading-ui/scripts/testing/test-entity-details-in-browser.js"
echo ""
echo "5. בדוק שכל הפונקציות זמינות (צריכות להיות 'function')"
echo "6. נסה לפתוח פרטי ישות מטבלה (לחץ על שורה או כפתור)"
echo ""
echo "✅ סימנים לבדיקה מוצלחת:"
echo "   • כל הפונקציות זמינות"
echo "   • מודל נפתח כשלוחצים על ישות"
echo "   • המודל מציג פרטים נכון"
echo "   • אין שגיאות בקונסולה"
echo ""



